# app.yaml
# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level-features
# https://cloud.google.com/appengine/docs/standard

runtime: java
env: flex

# pick Java 17 on Ubuntu 22
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"

# Spring Boot & Cloud SQL settings
env_variables:
  # use prod profile
  SPRING_PROFILES_ACTIVE: "prod"

  # force Postgres driver in prod
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"

  # your Cloud SQL settings
  INSTANCE_CONNECTION_NAME: "sopra-fs25-group-15-server:europe-west1:sopra-postgres"
  DB_NAME:             "soprafs25db"
  DB_USER:             "postgres"
  DB_PASS:             "FS25-Group15"

# mount the built-in Cloud SQL proxy so your app can talk over the Unix socket
beta_settings:
  cloud_sql_instances: "sopra-fs25-group-15-server:europe-west1:sopra-postgres"
